export const LOADER = 'LOADER';
export const SUBSCRIBE = 'SUBSCRIBE';
export const REQUEST_BEGIN = 'REQUEST_BEGIN';
export const REQUEST_FINISH = 'REQUEST_FINISH';
export const LOAD_PROMOTIONAL_VIDEOS = 'LOAD_PROMOTIONAL_VIDEOS';
export const LOAD_SOCIAL_FEEDS = 'LOAD_SOCIAL_FEEDS';